version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2022.09
    steps:
      - add_ssh_keys
      - run:
          name: Add GitHub SSH Key to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Clone Repos
          command: |
            git clone --recurse-submodules git@github.com:YunTechAi-FreeSpaceTechnic/ModelServer.git
            git clone --recurse-submodules $CIRCLE_REPOSITORY_URL ./ModelServer/model
      - setup_remote_docker
      - run:
          name: Login to GitHub Container Registry
          command: |
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${CIRCLE_PROJECT_USERNAME}" --password-stdin
      - run:
          name: Build Docker image
          command: |
            VERSION=${CIRCLE_TAG}
            IMAGE_NAME="ghcr.io/${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME,,}"

            docker build --build-arg MODEL=model -t $IMAGE_NAME:latest ModelServer

            echo "Push Docker Image to GHCR"
            docker push $IMAGE_NAME:latest

            if [ -n "$CIRCLE_TAG" ]; then
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:${VERSION}
              docker push $IMAGE_NAME:$VERSION
            fi

workflows:
  build-with--model-server:
    jobs:
      - build-docker-image:
          context: GLOBAL_ENV
          filters:
            tags:
              only:
                - "*"
